# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 341, 41))
        self.label.setStyleSheet("font: 16pt \"Consolas\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 30, 681, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 50, 681, 81))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.start_hour_1 = QtWidgets.QLineEdit(self.frame)
        self.start_hour_1.setGeometry(QtCore.QRect(0, 50, 21, 21))
        self.start_hour_1.setText("")
        self.start_hour_1.setObjectName("start_hour_1")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(23, 50, 20, 21))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.start_minute_1 = QtWidgets.QLineEdit(self.frame)
        self.start_minute_1.setGeometry(QtCore.QRect(30, 50, 21, 21))
        self.start_minute_1.setText("")
        self.start_minute_1.setObjectName("start_minute_1")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(53, 50, 21, 21))
        self.label_4.setObjectName("label_4")
        self.calc1_label = QtWidgets.QLabel(self.frame)
        self.calc1_label.setGeometry(QtCore.QRect(0, 0, 161, 20))
        self.calc1_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.calc1_label.setObjectName("calc1_label")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.machine_time_1 = QtWidgets.QLineEdit(self.frame)
        self.machine_time_1.setGeometry(QtCore.QRect(107, 50, 31, 21))
        self.machine_time_1.setObjectName("machine_time_1")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(140, 50, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.change_time_1 = QtWidgets.QLineEdit(self.frame)
        self.change_time_1.setGeometry(QtCore.QRect(207, 50, 31, 21))
        self.change_time_1.setObjectName("change_time_1")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(280, 30, 111, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.parts_count_1 = QtWidgets.QLineEdit(self.frame)
        self.parts_count_1.setGeometry(QtCore.QRect(317, 50, 31, 21))
        self.parts_count_1.setObjectName("parts_count_1")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(350, 50, 21, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(397, 30, 91, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.other_time_1 = QtWidgets.QLineEdit(self.frame)
        self.other_time_1.setGeometry(QtCore.QRect(427, 50, 31, 21))
        self.other_time_1.setText("")
        self.other_time_1.setObjectName("other_time_1")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(460, 50, 21, 21))
        self.label_13.setObjectName("label_13")
        self.auto_dinner_checkbox = QtWidgets.QCheckBox(self.frame)
        self.auto_dinner_checkbox.setGeometry(QtCore.QRect(470, 0, 211, 21))
        self.auto_dinner_checkbox.setObjectName("auto_dinner_checkbox")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(490, 30, 16, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.calc_button = QtWidgets.QPushButton(self.frame)
        self.calc_button.setGeometry(QtCore.QRect(510, 20, 161, 21))
        self.calc_button.setObjectName("calc_button")
        self.result_line = QtWidgets.QLineEdit(self.frame)
        self.result_line.setGeometry(QtCore.QRect(560, 50, 61, 21))
        self.result_line.setFrame(True)
        self.result_line.setClearButtonEnabled(True)
        self.result_line.setObjectName("result_line")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 681, 81))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.start_hour_2 = QtWidgets.QLineEdit(self.frame_2)
        self.start_hour_2.setGeometry(QtCore.QRect(0, 50, 21, 21))
        self.start_hour_2.setText("")
        self.start_hour_2.setObjectName("start_hour_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.calc_button_2 = QtWidgets.QPushButton(self.frame_2)
        self.calc_button_2.setGeometry(QtCore.QRect(510, 20, 161, 21))
        self.calc_button_2.setObjectName("calc_button_2")
        self.auto_dinner_checkbox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.auto_dinner_checkbox_2.setGeometry(QtCore.QRect(470, 0, 211, 21))
        self.auto_dinner_checkbox_2.setObjectName("auto_dinner_checkbox_2")
        self.machine_time_2 = QtWidgets.QLineEdit(self.frame_2)
        self.machine_time_2.setGeometry(QtCore.QRect(107, 50, 31, 21))
        self.machine_time_2.setObjectName("machine_time_2")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(280, 30, 111, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(397, 30, 91, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(240, 50, 21, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.change_time_2 = QtWidgets.QLineEdit(self.frame_2)
        self.change_time_2.setGeometry(QtCore.QRect(207, 50, 31, 21))
        self.change_time_2.setObjectName("change_time_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(140, 50, 31, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(23, 50, 20, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_2)
        self.label_20.setGeometry(QtCore.QRect(80, 30, 91, 21))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.start_minute_2 = QtWidgets.QLineEdit(self.frame_2)
        self.start_minute_2.setGeometry(QtCore.QRect(30, 50, 21, 21))
        self.start_minute_2.setText("")
        self.start_minute_2.setObjectName("start_minute_2")
        self.result_line_2 = QtWidgets.QLineEdit(self.frame_2)
        self.result_line_2.setGeometry(QtCore.QRect(560, 50, 61, 21))
        self.result_line_2.setFrame(True)
        self.result_line_2.setClearButtonEnabled(True)
        self.result_line_2.setObjectName("result_line_2")
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setGeometry(QtCore.QRect(460, 50, 21, 21))
        self.label_22.setObjectName("label_22")
        self.other_time_2 = QtWidgets.QLineEdit(self.frame_2)
        self.other_time_2.setGeometry(QtCore.QRect(427, 50, 31, 21))
        self.other_time_2.setText("")
        self.other_time_2.setObjectName("other_time_2")
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(490, 30, 16, 41))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.calc2_label = QtWidgets.QLabel(self.frame_2)
        self.calc2_label.setGeometry(QtCore.QRect(0, 0, 171, 20))
        self.calc2_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.calc2_label.setObjectName("calc2_label")
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setGeometry(QtCore.QRect(53, 50, 21, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_2)
        self.label_24.setGeometry(QtCore.QRect(353, 50, 21, 21))
        self.label_24.setObjectName("label_24")
        self.fiinish_hour_2 = QtWidgets.QLineEdit(self.frame_2)
        self.fiinish_hour_2.setGeometry(QtCore.QRect(300, 50, 21, 21))
        self.fiinish_hour_2.setText("")
        self.fiinish_hour_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fiinish_hour_2.setCursorPosition(0)
        self.fiinish_hour_2.setObjectName("fiinish_hour_2")
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setGeometry(QtCore.QRect(323, 50, 20, 21))
        self.label_21.setObjectName("label_21")
        self.finish_minute_2 = QtWidgets.QLineEdit(self.frame_2)
        self.finish_minute_2.setGeometry(QtCore.QRect(330, 50, 21, 21))
        self.finish_minute_2.setText("")
        self.finish_minute_2.setObjectName("finish_minute_2")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 681, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.load_button = QtWidgets.QPushButton(Form)
        self.load_button.setGeometry(QtCore.QRect(340, 10, 351, 23))
        self.load_button.setAutoDefault(False)
        self.load_button.setDefault(False)
        self.load_button.setFlat(False)
        self.load_button.setObjectName("load_button")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(10, 210, 681, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(30, 250, 641, 161))
        self.label_25.setObjectName("label_25")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Калькулятор выработки</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "ч"))
        self.label_2.setText(_translate("Form", "Время начала"))
        self.label_4.setText(_translate("Form", "мин"))
        self.calc1_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Расчет времени окончания</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "Машинное время"))
        self.label_7.setText(_translate("Form", "мин"))
        self.label_8.setText(_translate("Form", "Время на замену"))
        self.label_9.setText(_translate("Form", "мин"))
        self.label_10.setText(_translate("Form", "Количество деталей"))
        self.label_11.setText(_translate("Form", "шт."))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\">Прочие простои</p></body></html>"))
        self.label_13.setText(_translate("Form", "мин"))
        self.auto_dinner_checkbox.setText(_translate("Form", "Автоматически учитывать перерывы"))
        self.calc_button.setText(_translate("Form", "Расчитать время окончания"))
        self.label_5.setText(_translate("Form", "Время начала"))
        self.calc_button_2.setText(_translate("Form", "Расчитать детали"))
        self.auto_dinner_checkbox_2.setText(_translate("Form", "Автоматически учитывать перерывы"))
        self.label_14.setText(_translate("Form", "Время окончания"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\">Прочие простои</p></body></html>"))
        self.label_16.setText(_translate("Form", "мин"))
        self.label_17.setText(_translate("Form", "Время на замену"))
        self.label_18.setText(_translate("Form", "мин"))
        self.label_19.setText(_translate("Form", "ч"))
        self.label_20.setText(_translate("Form", "Машинное время"))
        self.label_22.setText(_translate("Form", "мин"))
        self.calc2_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Расчет количества деталей</span></p></body></html>"))
        self.label_23.setText(_translate("Form", "мин"))
        self.label_24.setText(_translate("Form", "мин"))
        self.label_21.setText(_translate("Form", "ч"))
        self.load_button.setText(_translate("Form", "Загрузить деталь из таблицы"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">только начал писать, еще не работает</span></p></body></html>"))
