# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(666, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Icons/Pauloruberto-Custom-Round-Yosemite-Python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_superzalupa = QtWidgets.QLabel(self.centralwidget)
        self.label_superzalupa.setGeometry(QtCore.QRect(9, 9, 321, 61))
        self.label_superzalupa.setMouseTracking(True)
        self.label_superzalupa.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_superzalupa.setAutoFillBackground(False)
        self.label_superzalupa.setStyleSheet("font: 32pt \"Agency FB\";")
        self.label_superzalupa.setObjectName("label_superzalupa")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setEnabled(True)
        self.label_path.setGeometry(QtCore.QRect(9, 76, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_path.setFont(font)
        self.label_path.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_path.setObjectName("label_path")
        self.backup_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.backup_checkbox.setGeometry(QtCore.QRect(492, 79, 165, 17))
        self.backup_checkbox.setMinimumSize(QtCore.QSize(165, 17))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.backup_checkbox.setFont(font)
        self.backup_checkbox.setAcceptDrops(False)
        self.backup_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backup_checkbox.setAutoFillBackground(False)
        self.backup_checkbox.setChecked(False)
        self.backup_checkbox.setTristate(False)
        self.backup_checkbox.setObjectName("backup_checkbox")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(9, 105, 648, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.fanuc_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.fanuc_list_widget.setEnabled(True)
        self.fanuc_list_widget.setGeometry(QtCore.QRect(10, 140, 321, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fanuc_list_widget.sizePolicy().hasHeightForWidth())
        self.fanuc_list_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.fanuc_list_widget.setFont(font)
        self.fanuc_list_widget.setAcceptDrops(False)
        self.fanuc_list_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.fanuc_list_widget.setObjectName("fanuc_list_widget")
        self.mazatrol_list_widget = QtWidgets.QListWidget(self.centralwidget)
        self.mazatrol_list_widget.setGeometry(QtCore.QRect(340, 140, 321, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mazatrol_list_widget.sizePolicy().hasHeightForWidth())
        self.mazatrol_list_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.mazatrol_list_widget.setFont(font)
        self.mazatrol_list_widget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.mazatrol_list_widget.setAutoFillBackground(False)
        self.mazatrol_list_widget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mazatrol_list_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.mazatrol_list_widget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mazatrol_list_widget.setLineWidth(1)
        self.mazatrol_list_widget.setResizeMode(QtWidgets.QListView.Adjust)
        self.mazatrol_list_widget.setViewMode(QtWidgets.QListView.ListMode)
        self.mazatrol_list_widget.setModelColumn(0)
        self.mazatrol_list_widget.setUniformItemSizes(False)
        self.mazatrol_list_widget.setBatchSize(100)
        self.mazatrol_list_widget.setWordWrap(False)
        self.mazatrol_list_widget.setSelectionRectVisible(False)
        self.mazatrol_list_widget.setObjectName("mazatrol_list_widget")
        self.rename_mazatrol_button = QtWidgets.QPushButton(self.centralwidget)
        self.rename_mazatrol_button.setGeometry(QtCore.QRect(340, 330, 321, 23))
        self.rename_mazatrol_button.setObjectName("rename_mazatrol_button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(9, 360, 648, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_info_window = QtWidgets.QLabel(self.centralwidget)
        self.label_info_window.setGeometry(QtCore.QRect(9, 369, 67, 16))
        self.label_info_window.setObjectName("label_info_window")
        self.info_window = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.info_window.setGeometry(QtCore.QRect(9, 388, 651, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_window.sizePolicy().hasHeightForWidth())
        self.info_window.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.info_window.setFont(font)
        self.info_window.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.info_window.setMouseTracking(False)
        self.info_window.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.info_window.setAcceptDrops(False)
        self.info_window.setFrameShape(QtWidgets.QFrame.Box)
        self.info_window.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.info_window.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.info_window.setObjectName("info_window")
        self.rename_fanuc_button = QtWidgets.QPushButton(self.centralwidget)
        self.rename_fanuc_button.setGeometry(QtCore.QRect(10, 330, 321, 23))
        self.rename_fanuc_button.setObjectName("rename_fanuc_button")
        self.label_mazatrol_list = QtWidgets.QLabel(self.centralwidget)
        self.label_mazatrol_list.setGeometry(QtCore.QRect(339, 120, 321, 20))
        self.label_mazatrol_list.setAutoFillBackground(False)
        self.label_mazatrol_list.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_mazatrol_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mazatrol_list.setObjectName("label_mazatrol_list")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(339, 29, 311, 21))
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.scaner_button = QtWidgets.QPushButton(self.centralwidget)
        self.scaner_button.setGeometry(QtCore.QRect(336, 76, 121, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaner_button.sizePolicy().hasHeightForWidth())
        self.scaner_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.scaner_button.setFont(font)
        self.scaner_button.setObjectName("scaner_button")
        self.scaner_path = QtWidgets.QLineEdit(self.centralwidget)
        self.scaner_path.setGeometry(QtCore.QRect(44, 77, 251, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaner_path.sizePolicy().hasHeightForWidth())
        self.scaner_path.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scaner_path.setFont(font)
        self.scaner_path.setMouseTracking(True)
        self.scaner_path.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.scaner_path.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scaner_path.setObjectName("scaner_path")
        self.label_fanuc_list = QtWidgets.QLabel(self.centralwidget)
        self.label_fanuc_list.setGeometry(QtCore.QRect(7, 120, 321, 20))
        self.label_fanuc_list.setAutoFillBackground(False)
        self.label_fanuc_list.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_fanuc_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fanuc_list.setObjectName("label_fanuc_list")
        self.scaner_path_dialog_button = QtWidgets.QToolButton(self.centralwidget)
        self.scaner_path_dialog_button.setGeometry(QtCore.QRect(300, 78, 25, 21))
        self.scaner_path_dialog_button.setObjectName("scaner_path_dialog_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 666, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.mazatrol_list_widget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Superzalupa 2"))
        self.label_superzalupa.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">SUPERZALUPA 2</span></p></body></html>"))
        self.label_path.setText(_translate("MainWindow", "Путь:"))
        self.backup_checkbox.setText(_translate("MainWindow", "Создать бэкап программ"))
        __sortingEnabled = self.fanuc_list_widget.isSortingEnabled()
        self.fanuc_list_widget.setSortingEnabled(False)
        self.fanuc_list_widget.setSortingEnabled(__sortingEnabled)
        self.mazatrol_list_widget.setSortingEnabled(False)
        __sortingEnabled = self.mazatrol_list_widget.isSortingEnabled()
        self.mazatrol_list_widget.setSortingEnabled(False)
        self.mazatrol_list_widget.setSortingEnabled(__sortingEnabled)
        self.rename_mazatrol_button.setText(_translate("MainWindow", "Переименовать Mazatrol программы"))
        self.label_info_window.setText(_translate("MainWindow", "<html><head/><body><p>Информация:</p></body></html>"))
        self.rename_fanuc_button.setText(_translate("MainWindow", "Переименовать Fanuc программы"))
        self.label_mazatrol_list.setText(_translate("MainWindow", "Программы Mazatrol"))
        self.scaner_button.setText(_translate("MainWindow", "Сканировать"))
        self.label_fanuc_list.setText(_translate("MainWindow", "Программы Fanuc"))
        self.scaner_path_dialog_button.setText(_translate("MainWindow", "..."))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Настройки"))
        self.action_3.setText(_translate("MainWindow", "Справка"))
        self.action_5.setText(_translate("MainWindow", "Выход"))
